USE
    SECOND_FLOOR_CAFE;
DROP TABLE IF EXISTS SYS_MENU;
CREATE TABLE SYS_MENU
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PERMS     VARCHAR(50) DEFAULT '' UNIQUE,
    CREATE_AT TIMESTAMP   DEFAULT NULL,
    UPDATE_AT TIMESTAMP   DEFAULT NULL,
    DELETE_AT TIMESTAMP   DEFAULT NULL
) CHARACTER SET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT 'SYS_MENU';
INSERT INTO SYS_MENU(ID, PERMS,CREATE_AT,UPDATE_AT)
values (1, 'login',now(),now()),
       (2, 'manage',now(),now()),
       (3, 'menuTest',now(),now());