USE SECOND_FLOOR_CAFE;
DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE
(
    ID      BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT             NOT NULL,
    ROLE_ID BIGINT             NOT NULL
) CHARACTER SET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT 'SYS_USER_ROLE';
ALTER TABLE SYS_USER_ROLE
    ADD CONSTRAINT FK_SYS_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID),
    ADD CONSTRAINT FK_SYS_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ID);
INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID)
VALUES (1, 5),
       (2, 3);