USE
second_floor_cafe;
DROP TABLE IF EXISTS SYS_ROLE_MENU;
CREATE TABLE SYS_ROLE_MENU
(
    ROLE_ID BIGINT NOT NULL,
    MENU_ID BIGINT NOT NULL
) CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_general_ci COMMENT 'user'