USE
    SECOND_FLOOR_CAFE;
DROP TABLE IF EXISTS SYS_ROLE_MENU;
CREATE TABLE SYS_ROLE_MENU
(
    ID      BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ROLE_ID BIGINT                            NOT NULL,
    MENU_ID BIGINT                            NOT NULL

) CHARACTER SET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT 'SYS_ROLE_MENU';
ALTER TABLE SYS_ROLE_MENU
    ADD CONSTRAINT FK_SYS_ROLE_MENU_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ID),
    ADD CONSTRAINT FK_SYS_ROLE_MENU_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES SYS_MENU (ID);
INSERT INTO SYS_ROLE_MENU(ROLE_ID, MENU_ID)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (2, 2),
       (2, 3),
       (3, 3),
       (5, 1),
       (5, 2),
       (5, 3);