USE SECOND_FLOOR_CAFE;
DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USERNAME     VARCHAR(100) UNIQUE                NOT NULL,
    PASSWORD     VARCHAR(255)                       NOT NULL,
    CHINESE_NAME VARCHAR(50) DEFAULT '',
    ENGLISH_NAME VARCHAR(50) DEFAULT '',
    EMAIL        VARCHAR(50) UNIQUE                NOT NULL,
    CREATE_AT    TIMESTAMP   DEFAULT NULL,
    UPDATE_AT    TIMESTAMP   DEFAULT NULL,
    DELETE_AT    TIMESTAMP   DEFAULT NULL
) CHARACTER SET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT 'SYS_USER';
INSERT INTO SYS_USER(ID, USERNAME, PASSWORD, CHINESE_NAME, ENGLISH_NAME, EMAIL, CREATE_AT, UPDATE_AT)
values (1, '003958', '003958', '許正坤', 'Kun', 'djpkendjpken@gmail.com', now(), now()),
       (2, '004015', '004015', '林郁晴', 'Melody', 'ching@gmail.com', now(), now());