USE second_floor_cafe;
DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE
(
    ID      BigINT primary key NOT NULL auto_increment,
    USER_ID BIGINT             NOT NULL,
    ROLE_ID BIGINT             NOT NULL
) CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_general_ci COMMENT 'SYS_USER_ROLE';
ALTER TABLE SYS_USER_ROLE
    ADD CONSTRAINT FK_SYS_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID),
    ADD CONSTRAINT FK_SYS_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ID);
INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID)
values (1, 5),
       (2, 3);