USE
    SECOND_FLOOR_CAFE;
DROP TABLE IF EXISTS MENU_DISH_PHOTO;
CREATE TABLE MENU_DISH_PHOTO
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MENU_DISH_ID BIGINT                            NOT NULL,
    DATA         BLOB                              NOT NULL
) CHARACTER SET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT 'MENU_DISH_PHOTO';
ALTER TABLE MENU_DISH_PHOTO
    ADD CONSTRAINT FK_MENU_DISH_PHOTO_MENU_DISH_ID FOREIGN KEY (MENU_DISH_ID) REFERENCES menu_dish_text (ID);
