USE
    SECOND_FLOOR_CAFE;
DROP TABLE IF EXISTS SCORE;
CREATE TABLE SCORE
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USER_ID    BIGINT                            NOT NULL,
    SCORE      INT                               NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT NULL,
    UPDATE_AT  TIMESTAMP DEFAULT NULL
) CHARACTER SET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT 'SYS_USER';
ALTER TABLE SCORE
    ADD CONSTRAINT FK_SCORE_USER_ID FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID);
